// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace G4G.Models
{
    public partial class Account
    {
        public Account()
        {
            Comment = new HashSet<Comment>();
            Content = new HashSet<Content>();
        }

        public int IdAccount { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Content> Content { get; set; }
    }
}