// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace G4G.Models
{
    public partial class Comment
    {
        public int IdComment { get; set; }
        public string Text { get; set; }
        public DateTime Posted { get; set; }
        public int AccountIdAccount { get; set; }
        public string AccountUsername { get; set; }
        public int ContentIdContent { get; set; }

        public virtual Account Account { get; set; }
        public virtual Content ContentIdContentNavigation { get; set; }
    }
}