// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace G4G.Models
{
    public partial class SubCategory
    {
        public SubCategory()
        {
            Content = new HashSet<Content>();
        }

        public int IdSubcategory { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public int CategoryIdCategory { get; set; }

        public virtual Category CategoryIdCategoryNavigation { get; set; }
        public virtual ICollection<Content> Content { get; set; }
    }
}